runtime: php81

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 15
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6
  target_concurrent_requests: 100

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 100

env_variables:
  # Put production environment variables here.
  APP_DEBUG: true
  APP_ENV: production
  APP_KEY: "base64:jPuCYpPRSSwT87gY065noDskfUaOiG/nivu70p1W2fw="
  APP_NAME: "api-warung-bersama"

  LOG_LEVEL: debug
